#pragma once

#include <juce_core/juce_core.h>

namespace AUREQ
{
    enum class AureqLanguage
    {
        PortugueseBR,
        English
    };

    enum class TextKey
    {
        Settings,
        Theme,
        Bypass,
        Reset,
        AddBand,
        Remove,
        SaveCurrentPreset,
        Genres,
        BySource,
        UserPresets,
        NoUserPresets,
        RefreshUserPresets,
        RevealPresetsFolder,
        DeleteUserPreset,
        RevealPresetsFolderFailed,
        RevealPresetsFolderFailedMessage,
        SavePresetFailed,
        SavePresetFailedMessage,
        SaveCurrentPresetTitle,
        SaveCurrentPresetMessage,
        Name,
        Save,
        Cancel,
        DeleteUserPresetTitle,
        DeleteUserPresetMessagePrefix,
        DeleteUserPresetMessageSuffix,
        Delete,
        DeletePresetFailed,
        DeletePresetFailedMessage,
        Ok,
        Undo,
        Redo,
        Language,
        PortugueseBR,
        English,
        CopyAToB,
        CopyBToA,
        CopyCurrentToOther,
        ResetBToCurrent,
        InputGain,
        OutputGain,
        Band,
        Frequency,
        Freq,
        Gain,
        QFactor,
        Range,
        Threshold,
        Thresh,
        Attack,
        Release,
        Slope,
        FilterType,
        ChannelMode,
        DynamicEQ,
        SelectBandToEdit,
        FooterProduct,
        Type,
        Active,
        On,
        Off,
        NotAvailable,
        ChannelShort,
        Bell,
        LowCut,
        HighCut,
        LowShelf,
        HighShelf,
        Notch,
        BandPass,
        Stereo,
        Mid,
        Side,
        Left,
        Right,
        Vocals,
        Drums,
        Bass808,
        Instruments,
        MixBusMaster,
        UtilityCleanup,
        Vocal,
        RapVocal,
        LeadVocal,
        BackingVocal,
        Choir,
        Adlibs,
        Accordion,
        Zabumba,
        Bass,
        Kick,
        Snare,
        SnareClap,
        HiHat,
        Percussion,
        Beat,
        BeatBus,
        DrumBus,
        Sample,
        ElectricGuitar,
        AcousticGuitar,
        Guitar,
        Viola,
        PianoKeys,
        Synth,
        Lead,
        LeadSynth,
        Pad,
        MixBus,
        Master
    };

    juce::String getText (TextKey key, AureqLanguage language);
    juce::String getFilterTypeText (int type, AureqLanguage language);
    juce::String getChannelModeText (int mode, AureqLanguage language);
    juce::String getCategoryText (const juce::String& category, AureqLanguage language);
    juce::String getSourceText (const juce::String& source, AureqLanguage language);
    juce::String languageToPreferenceValue (AureqLanguage language);
    AureqLanguage languageFromPreferenceValue (const juce::String& value);
}
